alias upip='pip install --upgrade pip'
alias act='source .venv/bin/activate'
alias vact='source venv/bin/activate'
alias dzi='find . -name "*:Zone.Identifier" -type f -delete'
alias gqp='git add .;git commit -m "Work done by `date`";git push'
alias p3='python3'
alias p3.10='python3.10'